spring.application.name=Animais Producao

spring.datasource.url=jdbc:postgresql://dpg-d097lmc9c44c7380sn8g-a.oregon-postgres.render.com:5432/animais_rp3g
spring.datasource.username=animais_rp3g_user
spring.datasource.password=YcXKWBZ5y4DA3Qh4PCGHGKcj3D86R4ie

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jackson.time-zone = America/Sao_Paulo